<h1 style="text-align: center;" markdown="1">TP2: Gradient Boost con tuneo de parametros</h1>
![](../data/icon_properati-data.png)

In [1]:
import numpy as np 
import pandas as pd

# plots
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
%pylab inline

# modules
import knn as knnlibrary

Populating the interactive namespace from numpy and matplotlib

/opt/conda/lib/python3.5/site-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['plt']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"

In [2]:
properties =knnlibrary.get_dataset()
properties.describe()

/opt/conda/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,geonames_id,lat,lon,price,price_aprox_local_currency,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses
count,3.863550e+05,334976.000000,334976.000000,4.154970e+05,4.154970e+05,4.154970e+05,309478.000000,3.773720e+05,2.580050e+05,3.358800e+05,48541.000000,253418.000000,4.412500e+04
mean,3.553040e+06,-34.713500,-59.164432,3.765010e+05,3.735169e+06,2.221532e+05,278.302348,5.464535e+03,1.886115e+03,5.386186e+03,15.386004,3.022879,4.403698e+03
std,3.771644e+05,2.264589,2.369852,1.291127e+06,6.073609e+06,3.600731e+05,2102.664846,3.255710e+06,3.499881e+03,2.049472e+04,121.113099,1.616920,9.935418e+04
min,3.427208e+06,-54.833014,-122.419415,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,5.000000e-05,1.000000,1.000000,1.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,6.948895e+06,52.619706,35.202660,6.500000e+08,8.212711e+08,5.000000e+07,200000.000000,2.000000e+09,1.271027e+06,4.000000e+06,7167.000000,40.000000,1.000150e+07

In [3]:
# filtro por CABA y GBA
properties_caba = properties[(properties['place_with_parent_names'].str.contains('Capital Federal') \
                             | properties['place_with_parent_names'].str.contains('Bs.As. G.B.A.'))]

properties_caba = properties_caba[properties_caba['price'].notnull() & properties_caba['price'] > 0 & properties_caba['place_name'].notnull()]

# eliminamos propiedades con mas de 54 pisos
properties_caba = properties_caba[properties_caba['floor'] <= 60]
# eliminamos propiedades con mas de 9 pisos - ver analisis
properties_caba = properties_caba[properties_caba['rooms'] <=  10]
# eliminamos propiedades con mas de 2000 m2 de superficie cubierta - ver analisis
properties_caba = properties_caba[(properties_caba['surface_covered_in_m2'] <= 4000) & (properties_caba['surface_covered_in_m2'] >= 0)]
# eliminamos propiedades con mas de 2000 m2 de superficie cubierta - ver analisis
properties_caba = properties_caba[(properties_caba['surface_total_in_m2']<= 6000)  & (properties_caba['surface_total_in_m2'] >= 0)]
properties_caba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11526 entries, 385 to 80073
Data columns (total 27 columns):
id                            11526 non-null object
created_on                    11526 non-null object
operation                     11526 non-null object
property_type                 11526 non-null object
place_name                    11526 non-null object
place_with_parent_names       11526 non-null object
country_name                  11526 non-null object
state_name                    11526 non-null object
geonames_id                   10009 non-null float64
lat-lon                       10364 non-null object
lat                           10364 non-null float64
lon                           10364 non-null float64
price                         11526 non-null float64
currency                      11526 non-null object
price_aprox_local_currency    11526 non-null float64
price_aprox_usd               11526 non-null float64
surface_total_in_m2           11526 non-null float64
surface_covered_in_m2         11526 non-null float64
price_usd_per_m2              11526 non-null float64
price_per_m2                  11526 non-null float64
floor                         11526 non-null float64
rooms                         11526 non-null float64
expenses                      5180 non-null float64
properati_url                 11526 non-null object
description                   11526 non-null object
title                         11526 non-null object
image_thumbnail               11510 non-null object
dtypes: float64(13), object(14)
memory usage: 2.5+ MB

In [4]:
# filtro columnas segun lo que hay en el dataset
attributes = ['created_on','property_type','place_name','place_with_parent_names',\
              'country_name','state_name','lat','lon','surface_total_in_m2','surface_covered_in_m2',\
              'floor','rooms', 'price']
properties_caba[attributes].info()
properties_caba_with_price_attributes = properties_caba[attributes]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11526 entries, 385 to 80073
Data columns (total 13 columns):
created_on                 11526 non-null object
property_type              11526 non-null object
place_name                 11526 non-null object
place_with_parent_names    11526 non-null object
country_name               11526 non-null object
state_name                 11526 non-null object
lat                        10364 non-null float64
lon                        10364 non-null float64
surface_total_in_m2        11526 non-null float64
surface_covered_in_m2      11526 non-null float64
floor                      11526 non-null float64
rooms                      11526 non-null float64
price                      11526 non-null float64
dtypes: float64(7), object(6)
memory usage: 1.2+ MB

In [5]:
from sklearn.preprocessing import LabelEncoder

properties_caba_with_price_attributes.fillna('NaN', inplace=True)
# atributos categoricos
encoder = LabelEncoder()

properties_caba_with_price_attributes['property_type'] = encoder.fit_transform(properties_caba_with_price_attributes[['property_type']])
#properties_caba_with_price_attributes['operation'] = encoder.fit_transform(properties_caba_with_price_attributes[['operation']])
properties_caba_with_price_attributes['place_name'] = encoder.fit_transform(properties_caba_with_price_attributes[['place_name']])
properties_caba_with_price_attributes['place_with_parent_names'] = encoder.fit_transform(properties_caba_with_price_attributes[['place_with_parent_names']])
properties_caba_with_price_attributes['country_name'] = encoder.fit_transform(properties_caba_with_price_attributes[['country_name']])
properties_caba_with_price_attributes['state_name'] = encoder.fit_transform(properties_caba_with_price_attributes[['state_name']])
properties_caba_with_price_attributes['created_on'] = encoder.fit_transform(properties_caba_with_price_attributes[['created_on']])
# completamos valores nan
from sklearn.preprocessing import Imputer
imputer_mean = Imputer(missing_values='NaN', strategy='mean', axis=0)
properties_caba_with_price_attributes["lat"] = imputer_mean.fit_transform(properties_caba_with_price_attributes[["lat"]])
properties_caba_with_price_attributes["lon"] = imputer_mean.fit_transform(properties_caba_with_price_attributes[["lon"]])

properties_caba_with_price_attributes.head()

/opt/conda/lib/python3.5/site-packages/pandas/core/frame.py:2762: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)
/opt/conda/lib/python3.5/site-packages/sklearn/preprocessing/label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,created_on,property_type,place_name,place_with_parent_names,country_name,state_name,lat,lon,surface_total_in_m2,surface_covered_in_m2,floor,rooms,price
385,335,1,94,128,0,3,-34.544033,-58.472911,74.0,74.0,2.0,3.0,135000.0
890,338,1,67,48,0,1,-34.648915,-58.796383,32.0,32.0,2.0,2.0,48000.0
1010,339,1,23,99,0,3,-34.599574,-58.378334,43.0,43.0,10.0,3.0,129000.0
1018,339,1,68,53,0,1,-34.651616,-58.623603,29.0,27.0,7.0,1.0,58000.0
1020,339,1,90,42,0,1,-34.513637,-58.496707,30.0,30.0,2.0,2.0,55000.0

In [6]:
# separamos el set de train
from sklearn.model_selection import train_test_split
import datetime

now = datetime.datetime.now()

# separamos el train de traing para validarlo luego usando un 30% de los datos
X, y = properties_caba_with_price_attributes.iloc[:, properties_caba_with_price_attributes.columns != 'price'].values, properties_caba_with_price_attributes.iloc[:, properties_caba_with_price_attributes.columns == 'price'].values
X_train, X_test, y_train, y_test = \
        train_test_split(X, y, test_size=0.2, random_state=200)
    
print(y_train)
    
len(X_test), len(X_train)

[[ 130000.]
 [  93000.]
 [ 179500.]
 ...,
 [ 107500.]
 [  60000.]
 [  84000.]]

(2306, 9220)

In [7]:
from sklearn.grid_search import GridSearchCV
from sklearn.ensemble import GradientBoostingRegressor

#Choose all predictors except target & IDcols
param_test1 = {'n_estimators': [1500,1700,2000]}
gbr = GradientBoostingRegressor(learning_rate=0.1, min_samples_split=500,min_samples_leaf=50,max_depth=8,
                          max_features='sqrt',subsample=0.8,random_state=10)

gsearch1 = GridSearchCV(estimator=gbr, param_grid = param_test1,iid=False, cv=10)
gsearch1.fit(X_train,y_train.ravel())

gsearch1.grid_scores_, gsearch1.best_params_, gsearch1.best_score_

/opt/conda/lib/python3.5/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/opt/conda/lib/python3.5/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

([mean: 0.75527, std: 0.06112, params: {'n_estimators': 1500},
  mean: 0.76070, std: 0.06040, params: {'n_estimators': 1700},
  mean: 0.76798, std: 0.05973, params: {'n_estimators': 2000}],
 {'n_estimators': 2000},
 0.7679757976719633)

In [8]:
# test max_depth and min_samples_split
param_test2 = {'max_depth':[5,7,9,11,13,15,17,19,21], 'min_samples_split':[200,400,600,800,1000,1200]}
gbr = GradientBoostingRegressor(learning_rate=0.1, n_estimators=100, max_features='sqrt', subsample=0.8, random_state=10)

gsearch2 = GridSearchCV(estimator=gbr,param_grid = param_test2, iid=False, cv=10)

gsearch2.fit(X_train,y_train.ravel())

gsearch2.grid_scores_, gsearch2.best_params_, gsearch2.best_score_

([mean: 0.58169, std: 0.06728, params: {'max_depth': 5, 'min_samples_split': 200},
  mean: 0.54295, std: 0.05484, params: {'max_depth': 5, 'min_samples_split': 400},
  mean: 0.53245, std: 0.06346, params: {'max_depth': 5, 'min_samples_split': 600},
  mean: 0.51175, std: 0.06048, params: {'max_depth': 5, 'min_samples_split': 800},
  mean: 0.48969, std: 0.06385, params: {'max_depth': 5, 'min_samples_split': 1000},
  mean: 0.48093, std: 0.06997, params: {'max_depth': 5, 'min_samples_split': 1200},
  mean: 0.64842, std: 0.06157, params: {'max_depth': 7, 'min_samples_split': 200},
  mean: 0.61373, std: 0.05648, params: {'max_depth': 7, 'min_samples_split': 400},
  mean: 0.58295, std: 0.06913, params: {'max_depth': 7, 'min_samples_split': 600},
  mean: 0.56097, std: 0.06582, params: {'max_depth': 7, 'min_samples_split': 800},
  mean: 0.54121, std: 0.07005, params: {'max_depth': 7, 'min_samples_split': 1000},
  mean: 0.52965, std: 0.06451, params: {'max_depth': 7, 'min_samples_split': 1200},
  mean: 0.68165, std: 0.06814, params: {'max_depth': 9, 'min_samples_split': 200},
  mean: 0.64444, std: 0.05975, params: {'max_depth': 9, 'min_samples_split': 400},
  mean: 0.61709, std: 0.06744, params: {'max_depth': 9, 'min_samples_split': 600},
  mean: 0.59461, std: 0.07122, params: {'max_depth': 9, 'min_samples_split': 800},
  mean: 0.56950, std: 0.06858, params: {'max_depth': 9, 'min_samples_split': 1000},
  mean: 0.55965, std: 0.06814, params: {'max_depth': 9, 'min_samples_split': 1200},
  mean: 0.70219, std: 0.07093, params: {'max_depth': 11, 'min_samples_split': 200},
  mean: 0.65910, std: 0.06885, params: {'max_depth': 11, 'min_samples_split': 400},
  mean: 0.63645, std: 0.07981, params: {'max_depth': 11, 'min_samples_split': 600},
  mean: 0.62049, std: 0.06869, params: {'max_depth': 11, 'min_samples_split': 800},
  mean: 0.59524, std: 0.07296, params: {'max_depth': 11, 'min_samples_split': 1000},
  mean: 0.56821, std: 0.07784, params: {'max_depth': 11, 'min_samples_split': 1200},
  mean: 0.72147, std: 0.06406, params: {'max_depth': 13, 'min_samples_split': 200},
  mean: 0.68100, std: 0.06217, params: {'max_depth': 13, 'min_samples_split': 400},
  mean: 0.65834, std: 0.06135, params: {'max_depth': 13, 'min_samples_split': 600},
  mean: 0.62995, std: 0.06105, params: {'max_depth': 13, 'min_samples_split': 800},
  mean: 0.60174, std: 0.07353, params: {'max_depth': 13, 'min_samples_split': 1000},
  mean: 0.58144, std: 0.06830, params: {'max_depth': 13, 'min_samples_split': 1200},
  mean: 0.72827, std: 0.06845, params: {'max_depth': 15, 'min_samples_split': 200},
  mean: 0.69168, std: 0.05939, params: {'max_depth': 15, 'min_samples_split': 400},
  mean: 0.66240, std: 0.06631, params: {'max_depth': 15, 'min_samples_split': 600},
  mean: 0.63742, std: 0.06902, params: {'max_depth': 15, 'min_samples_split': 800},
  mean: 0.61040, std: 0.07277, params: {'max_depth': 15, 'min_samples_split': 1000},
  mean: 0.58559, std: 0.06917, params: {'max_depth': 15, 'min_samples_split': 1200},
  mean: 0.74545, std: 0.06433, params: {'max_depth': 17, 'min_samples_split': 200},
  mean: 0.69836, std: 0.06648, params: {'max_depth': 17, 'min_samples_split': 400},
  mean: 0.67138, std: 0.07006, params: {'max_depth': 17, 'min_samples_split': 600},
  mean: 0.64226, std: 0.07341, params: {'max_depth': 17, 'min_samples_split': 800},
  mean: 0.60738, std: 0.07310, params: {'max_depth': 17, 'min_samples_split': 1000},
  mean: 0.59315, std: 0.07106, params: {'max_depth': 17, 'min_samples_split': 1200},
  mean: 0.74752, std: 0.06640, params: {'max_depth': 19, 'min_samples_split': 200},
  mean: 0.70903, std: 0.06140, params: {'max_depth': 19, 'min_samples_split': 400},
  mean: 0.67590, std: 0.06958, params: {'max_depth': 19, 'min_samples_split': 600},
  mean: 0.64634, std: 0.07023, params: {'max_depth': 19, 'min_samples_split': 800},
  mean: 0.61490, std: 0.07927, params: {'max_depth': 19, 'min_samples_split': 1000},
  mean: 0.59381, std: 0.07791, params: {'max_depth': 19, 'min_samples_split': 1200},
  mean: 0.74890, std: 0.07057, params: {'max_depth': 21, 'min_samples_split': 200},
  mean: 0.71239, std: 0.07128, params: {'max_depth': 21, 'min_samples_split': 400},
  mean: 0.67724, std: 0.07729, params: {'max_depth': 21, 'min_samples_split': 600},
  mean: 0.65454, std: 0.06719, params: {'max_depth': 21, 'min_samples_split': 800},
  mean: 0.62000, std: 0.07428, params: {'max_depth': 21, 'min_samples_split': 1000},
  mean: 0.59481, std: 0.06930, params: {'max_depth': 21, 'min_samples_split': 1200}],
 {'max_depth': 21, 'min_samples_split': 200},
 0.7488962546073363)

In [9]:
# test min_samples_spliy and min_samples_leaf
param_test3 = {'min_samples_split':[200,400,600,800,1000], 'min_samples_leaf':[100,200,400,600,800]}
gbr = GradientBoostingRegressor(max_depth=21, learning_rate=0.1, n_estimators=100, max_features='sqrt', 
                                subsample=0.8, random_state=10)

gsearch3 = GridSearchCV(estimator=gbr, param_grid=param_test3, iid=False, cv=10)
gsearch3.fit(X_train,y_train.ravel())

gsearch3.grid_scores_, gsearch3.best_params_, gsearch3.best_score_
# no set min_samples_leaf

([mean: 0.61516, std: 0.06764, params: {'min_samples_split': 200, 'min_samples_leaf': 100},
  mean: 0.51619, std: 0.06053, params: {'min_samples_split': 200, 'min_samples_leaf': 200},
  mean: 0.38652, std: 0.04440, params: {'min_samples_split': 200, 'min_samples_leaf': 400},
  mean: 0.30568, std: 0.03459, params: {'min_samples_split': 200, 'min_samples_leaf': 600},
  mean: 0.25394, std: 0.02548, params: {'min_samples_split': 200, 'min_samples_leaf': 800}],
 {'min_samples_leaf': 100, 'min_samples_split': 200},
 0.615163245435071)

In [10]:
# test max_features
param_test4 = {'max_features':[2,4,7]}
gbr = GradientBoostingRegressor(max_depth=21, learning_rate=0.1, n_estimators=100, max_features='sqrt', 
                                min_samples_split=200, subsample=0.8, random_state=10)

gsearch4 = GridSearchCV(estimator=gbr, param_grid=param_test4, iid=False, cv=10)
gsearch4.fit(X_train,y_train.ravel())

gsearch4.grid_scores_, gsearch4.best_params_, gsearch4.best_score_

([mean: 0.73249, std: 0.07591, params: {'max_features': 2},
  mean: 0.75484, std: 0.07394, params: {'max_features': 4},
  mean: 0.75655, std: 0.06323, params: {'max_features': 7}],
 {'max_features': 7},
 0.7565548379445033)

In [13]:
# test subsample
param_test5 = {'subsample':[0.8,0.85,0.9,0.95,1]}
gbr = GradientBoostingRegressor(max_depth=21, learning_rate=0.1, n_estimators=100, max_features=7, 
                                 min_samples_split=200, subsample=0.8, random_state=10)

gsearch5 = GridSearchCV(estimator=gbr, param_grid=param_test5, iid=False, cv=10)
gsearch5.fit(X_train,y_train.ravel())

gsearch5.grid_scores_, gsearch5.best_params_, gsearch5.best_score_

([mean: 0.75655, std: 0.06323, params: {'subsample': 0.8},
  mean: 0.76246, std: 0.06442, params: {'subsample': 0.85},
  mean: 0.76433, std: 0.06466, params: {'subsample': 0.9},
  mean: 0.76587, std: 0.06798, params: {'subsample': 0.95},
  mean: 0.75673, std: 0.07136, params: {'subsample': 1}],
 {'subsample': 0.95},
 0.7658658645128675)

## Aumentando los estimadores y disminuyendo el learning rate

In [30]:
from sklearn.metrics import r2_score, mean_squared_error

gbr = GradientBoostingRegressor(max_depth=21, learning_rate=0.025, n_estimators=2000, max_features=7, 
                                 min_samples_split=200, subsample=0.95, random_state=10)

gbr.fit(X_train,y_train.ravel())
r2_score(y_test.ravel(), gbr.predict(X_test))

0.83033177177771911

# TEST

In [31]:
# leemos set de test
test_df = pd.read_csv('../data/test/properati_dataset_testing_noprice.csv', low_memory=False)
test_df.head()

,id,created_on,property_type,operation,place_name,place_with_parent_names,country_name,state_name,lat-lon,lat,lon,surface_total_in_m2,surface_covered_in_m2,floor,rooms,expenses,description
0,3632,2017-08-24,departamento,venta,Puerto Madero,|Argentina|Capital Federal|Puerto Madero|,Argentina,Capital Federal,"-34.6109877599,-58.3634635778",-34.610988,-58.363464,0.0,NaN,NaN,NaN,NaN,Edificio BA Houses situado frente al Dique 3 d...
1,3633,2017-08-25,departamento,venta,Buenos Aires Interior,|Argentina|Buenos Aires Interior|,Argentina,Buenos Aires Interior,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,El departamento cuenta con un living-comedor a...
2,2263404,2017-08-01,departamento,venta,Palermo Soho,|Argentina|Capital Federal|Palermo|Palermo Soho|,Argentina,Capital Federal,"-34.5893633232,-58.4128798588",-34.589363,-58.412880,53.0,48.0,NaN,NaN,1500,IMPECABLE TORRE COY III – DEPA...
3,2263405,2017-08-01,departamento,venta,Chacarita,|Argentina|Capital Federal|Chacarita|,Argentina,Capital Federal,NaN,NaN,NaN,39.0,39.0,NaN,NaN,NaN,AMBIENTE DIVISIBLE CON PISOS D...
4,2263406,2017-08-01,departamento,venta,Chacarita,|Argentina|Capital Federal|Chacarita|,Argentina,Capital Federal,NaN,NaN,NaN,51.0,51.0,NaN,NaN,NaN,LIVING COMEDOR CON PISOS DE PO...

In [32]:
# transformamos atributos categoricos
test_df['place_name'] = encoder.fit_transform(test_df[['place_name']])
test_df['state_name'] = encoder.fit_transform(test_df[['state_name']])
test_df['place_with_parent_names'] = encoder.fit_transform(test_df[['place_with_parent_names']])
test_df['property_type'] = encoder.fit_transform(test_df[['property_type']])
test_df['created_on'] = encoder.fit_transform(test_df[['created_on']])
test_df['country_name'] = encoder.fit_transform(test_df[['country_name']])

X_test_df = test_df[['created_on','property_type','place_name','place_with_parent_names',\
              'country_name','state_name','lat','lon','surface_total_in_m2','surface_covered_in_m2',\
              'floor','rooms']]

# completamos valores nan
from sklearn.preprocessing import Imputer
imputer_mean = Imputer(missing_values='NaN', strategy='mean', axis=0)
X_test_df['floor'] = X_test_df[['floor']].fillna(1)
X_test_df['rooms'] = X_test_df[['rooms']].fillna(1)

X_test_df["surface_total_in_m2"] = imputer_mean.fit_transform(X_test_df[["surface_total_in_m2"]])
X_test_df["surface_covered_in_m2"] = imputer_mean.fit_transform(X_test_df[["surface_covered_in_m2"]])
X_test_df["lat"] = imputer_mean.fit_transform(X_test_df[["lat"]])
X_test_df["lon"] = imputer_mean.fit_transform(X_test_df[["lon"]])

X_test_df.info()

/opt/conda/lib/python3.5/site-packages/sklearn/preprocessing/label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14166 entries, 0 to 14165
Data columns (total 12 columns):
created_on                 14166 non-null int64
property_type              14166 non-null int64
place_name                 14166 non-null int64
place_with_parent_names    14166 non-null int64
country_name               14166 non-null int64
state_name                 14166 non-null int64
lat                        14166 non-null float64
lon                        14166 non-null float64
surface_total_in_m2        14166 non-null float64
surface_covered_in_m2      14166 non-null float64
floor                      14166 non-null float64
rooms                      14166 non-null float64
dtypes: float64(6), int64(6)
memory usage: 1.3 MB

/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [33]:
# prediccion del set de test
#knn = KNeighborsRegressor(n_neighbors=best_k, weights='distance', p=best_p)
#knn.fit(X_train_std[:, k_param], y_train)
X_test_df['prediction'] = gbr.predict(X_test_df)
X_test_df.head(10)

/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,created_on,property_type,place_name,place_with_parent_names,country_name,state_name,lat,lon,surface_total_in_m2,surface_covered_in_m2,floor,rooms,prediction
0,23,1,152,219,0,4,-34.610988,-58.363464,0.0,359.471588,1.0,1.0,495555.772149
1,24,1,29,180,0,3,-34.629923,-58.465820,0.0,359.471588,1.0,1.0,420762.158865
2,0,1,136,210,0,4,-34.589363,-58.412880,53.0,48.000000,1.0,1.0,145427.192720
3,0,1,40,193,0,4,-34.629923,-58.465820,39.0,39.000000,1.0,1.0,125233.556642
4,0,1,40,193,0,4,-34.629923,-58.465820,51.0,51.000000,1.0,1.0,120996.487073
5,0,1,40,193,0,4,-34.629923,-58.465820,39.0,39.000000,1.0,1.0,125233.556642
6,0,1,40,193,0,4,-34.629923,-58.465820,39.0,39.000000,1.0,1.0,125233.556642
7,0,1,40,193,0,4,-34.629923,-58.465820,39.0,39.000000,1.0,1.0,125233.556642
8,0,1,47,195,0,4,-34.578721,-58.457095,67.0,67.000000,1.0,1.0,238462.379440
9,0,1,7,184,0,4,-34.629923,-58.465820,47.0,47.000000,1.0,1.0,88981.344886

In [34]:
# guardo el file
output = pd.DataFrame( data={"id":test_df["id"], "price_usd":X_test_df['prediction']} )
output.to_csv( "../data/result/result_gbv02_"+str(now)+".csv", index=False, quoting=3 )